// Copyright (c) 2021 Gitpod GmbH. All rights reserved.
// Licensed under the GNU Affero General Public License (AGPL).
// See License-AGPL.txt in the project root for license information.

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.gitpod.test;

import java.util.concurrent.TimeUnit;

import io.gitpod.supervisor.api.Token.GetTokenRequest;
import io.gitpod.supervisor.api.Token.GetTokenResponse;
import io.gitpod.supervisor.api.TokenServiceGrpc;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;

public class App {
    public void getGreeting() throws Exception {
        System.out.println("hello");

        String supervisorAddr = "localhost:22999";
        ManagedChannel channel = ManagedChannelBuilder.forTarget(supervisorAddr).usePlaintext().build();
        try {
            this.callGetToken(channel);
        } finally {
            channel.shutdownNow().awaitTermination(5, TimeUnit.SECONDS);
        }
    }

    private void callGetToken(ManagedChannel channel) throws Exception {
        TokenServiceGrpc.TokenServiceBlockingStub blockingStub = TokenServiceGrpc.newBlockingStub(channel);
        GetTokenRequest request = GetTokenRequest.newBuilder().setHost("github.com").setKind("git").build();
        GetTokenResponse response = blockingStub.getToken(request);
        System.out.println("user: " + response.getUser());
        System.out.println("token: " + response.getToken());
    }

    public static void main(String[] args) throws Exception {
        new App().getGreeting();
    }
}
